import assert from 'node:assert/strict';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import zlib from 'node:zlib';
import { after, test, type TestContext } from 'node:test';
import { detectGame } from '../src/detect/index.ts';
import { uninstallReceipt } from '../src/install/apply.ts';
import { loadRegistry } from '../src/registry/index.ts';
import type { InstallReceipt } from '../src/types.ts';
import { previewTranslatorMaintenance, runTranslatorMaintenance, type TranslatorMaintenancePreview } from '../../desktop/src/translator-maintenance.ts';
import { cleanupFixtures, dllWithVersion, fakeExe, fixtureRoot, makeGame, sha256, writeReceiptFile } from './fixtures.ts';

const reg = loadRegistry();
const PLUGIN = 'BepInEx/plugins/XUnity.AutoTranslator/XUnity.AutoTranslator.Plugin.Core.dll';
const COMMON = 'BepInEx/core/XUnity.Common.dll';
const CONFIG = 'BepInEx/config/AutoTranslatorConfig.ini';
const OTHER = 'BepInEx/plugins/OtherMod.dll';
const LOADER = 'BepInEx/core/BepInEx.dll';
const FONT = 'arialuni_sdf_u2021';
const RECEIPT = '.indiedeck/receipts/translator-xunity-autotranslator.json';
const TRANSLATION = 'BepInEx/Translation/ko/Text/_AutoGeneratedTranslations.txt';
const USER_CONFIG = '[Service]\nEndpoint=PapagoTranslate\n[General]\nLanguage=ko\nFromLanguage=ja\n[Behaviour]\nFallbackFontTextMeshPro=arialuni_sdf_u2021\n[Custom]\nKeep=mine\n';
after(() => cleanupFixtures());

function game(name: string, extra: Record<string, string | Buffer> = {}) {
  const root = makeGame(`translator-maintenance-${name}`, {
    'Game.exe': fakeExe(0x8664), 'UnityPlayer.dll': 'isolated fixture',
    'Game_Data/Managed/Assembly-CSharp.dll': 'isolated Mono assembly',
    'Game_Data/globalgamemanagers': '2021.3.16f1',
    [LOADER]: dllWithVersion('5.4.23.5'), [PLUGIN]: dllWithVersion('5.5.2'), [COMMON]: dllWithVersion('5.5.2'),
    [CONFIG]: USER_CONFIG, [OTHER]: 'another user-owned mod', [FONT]: 'installed user font',
    [TRANSLATION]: 'hello=안녕', ...extra,
  });
  const profile = detectGame(reg, root, { deep: true });
  assert.ok(profile, 'the isolated fixture is a recognised Unity game');
  assert.equal(profile.engineId, 'unity');
  assert.equal(profile.unity?.backend, 'mono');
  return profile;
}
const bytes = (root: string, rel: string) => fs.readFileSync(path.join(root, rel));

function crc32(buffer: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of buffer) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ ((crc & 1) ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function zip(files: Record<string, string | Buffer>, deflate = false, declaredSize?: number): Buffer {
  const locals: Buffer[] = [], centrals: Buffer[] = [];
  let offset = 0;
  for (const [name, value] of Object.entries(files)) {
    const data = Buffer.isBuffer(value) ? value : Buffer.from(value);
    const compressed = deflate ? zlib.deflateRawSync(data) : data;
    const encoded = Buffer.from(name);
    const local = Buffer.alloc(30 + encoded.length), central = Buffer.alloc(46 + encoded.length);
    local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4);
    local.writeUInt16LE(deflate ? 8 : 0, 8);
    local.writeUInt32LE(crc32(data), 14); local.writeUInt32LE(compressed.length, 18); local.writeUInt32LE(declaredSize ?? data.length, 22);
    local.writeUInt16LE(encoded.length, 26); encoded.copy(local, 30);
    central.writeUInt32LE(0x02014b50, 0); central.writeUInt16LE(20, 4); central.writeUInt16LE(20, 6);
    central.writeUInt16LE(deflate ? 8 : 0, 10);
    central.writeUInt32LE(crc32(data), 16); central.writeUInt32LE(compressed.length, 20); central.writeUInt32LE(declaredSize ?? data.length, 24);
    central.writeUInt16LE(encoded.length, 28); central.writeUInt32LE(offset, 42); encoded.copy(central, 46);
    locals.push(local, compressed); centrals.push(central); offset += local.length + compressed.length;
  }
  const cd = Buffer.concat(centrals), end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(centrals.length, 8); end.writeUInt16LE(centrals.length, 10);
  end.writeUInt32LE(cd.length, 12); end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, cd, end]);
}

async function withDownload<T>(preview: TranslatorMaintenancePreview, payload: Buffer, action: () => Promise<T>, duringDownload?: () => void): Promise<T> {
  const original = globalThis.fetch;
  const asset = preview.context.plan?.steps.find((step) => step.action === 'download')?.source?.asset;
  assert.ok(asset, 'the fixture resolves a standard registered release asset');
  globalThis.fetch = async (input) => {
    const url = String(input);
    if (url.startsWith('https://api.github.com/repos/')) return new Response(JSON.stringify({ tag_name: 'v5.6.1', assets: [{ name: asset, browser_download_url: `https://maintenance.invalid/${asset}`, size: payload.length }] }), { status: 200 });
    assert.equal(url, `https://maintenance.invalid/${asset}`);
    duringDownload?.();
    return new Response(payload, { status: 200, headers: { 'content-length': String(payload.length) } });
  };
  try { return await action(); } finally { globalThis.fetch = original; }
}
const replacement = () => zip({ [PLUGIN]: dllWithVersion('5.6.1'), [COMMON]: dllWithVersion('5.6.1'), 'BepInEx/plugins/XUnity.AutoTranslator/Translators/GoogleTranslate.dll': 'isolated endpoint DLL' });
const cache = (name: string) => ({ cacheDir: path.join(fixtureRoot(), `maintenance-cache-${name}`) });

function own(profile: ReturnType<typeof game>, entries: InstallReceipt['entries']) {
  return writeReceiptFile(profile.path, { version: '5.5.2', variantId: 'bepinex', entries });
}
function createEntries(root: string, names: string[]): InstallReceipt['entries'] {
  return names.map((rel) => ({ path: rel, operation: 'create', sha256: sha256(bytes(root, rel)) }));
}

test('read-only preview lists exact recognised unmanaged duplicates, preserving unrelated mods and user data', async () => {
  const profile = game('duplicate', { 'Mods/XUnity.AutoTranslator.Plugin.MelonMod.dll': dllWithVersion('5.4.0') });
  const before = bytes(profile.path, PLUGIN);
  const preview = await previewTranslatorMaintenance(reg, profile, { targetLanguage: 'ko' });
  assert.equal(preview.removeEligible, true);
  assert.equal(preview.reinstallEligible, false, 'an existing unmanaged shared dependency is a preflight reinstall conflict');
  assert.equal(preview.reinstallBlockReasonKey, 'ui.maintenance.reason.ownership');
  assert.ok(preview.files.some((file) => file.path === 'Mods/XUnity.AutoTranslator.Plugin.MelonMod.dll'));
  assert.ok(preview.files.every((file) => !file.managed));
  assert.ok(!preview.files.some((file) => [CONFIG, OTHER, LOADER, FONT, TRANSLATION, 'Game.exe'].includes(file.path)));
  assert.deepEqual(bytes(profile.path, PLUGIN), before);
  assert.equal(fs.existsSync(path.join(profile.path, '.indiedeck')), false, 'preview writes no metadata');
});

test('remove quarantines exact existing files and canonical metadata, never deletes host/config/translations/font/mod receipts', async () => {
  const profile = game('remove');
  own(profile, createEntries(profile.path, [PLUGIN, COMMON, CONFIG, FONT]));
  writeReceiptFile(profile.path, { kind: 'font', componentId: FONT, entries: createEntries(profile.path, [FONT]) });
  const fontReceipt = bytes(profile.path, `.indiedeck/receipts/font-${FONT}.json`);
  const metadata = bytes(profile.path, RECEIPT);
  const before = new Map([CONFIG, OTHER, LOADER, FONT, TRANSLATION, 'Game.exe'].map((rel) => [rel, bytes(profile.path, rel)]));
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, true);
  const result = await runTranslatorMaintenance(preview, 'remove');
  assert.equal(result.mutationStatus, 'committed');
  assert.equal(result.rollbackStatus, 'not-run');
  assert.equal(fs.existsSync(path.join(profile.path, PLUGIN)), false);
  assert.equal(fs.existsSync(path.join(profile.path, RECEIPT)), false);
  assert.equal(fs.existsSync(path.join(profile.path, 'BepInEx/plugins/XUnity.AutoTranslator')), false, 'empty dedicated folder is pruned without recursive deletion');
  for (const [rel, content] of before) assert.deepEqual(bytes(profile.path, rel), content);
  assert.deepEqual(bytes(profile.path, `.indiedeck/receipts/font-${FONT}.json`), fontReceipt);
  assert.deepEqual(fs.readFileSync(path.join(result.backupDirectory, 'files', RECEIPT)), metadata);
  const manifest = JSON.parse(fs.readFileSync(result.manifestPath, 'utf8'));
  assert.equal(manifest.status, 'committed');
  assert.equal(manifest.mode, 'remove');
  assert.ok(manifest.files.some((file: { path: string }) => file.path === PLUGIN));
});

test('unmanaged reinstall downloads before cleanup, preserves config/font bytes, and uninstall cannot resurrect superseded translator files', async () => {
  const profile = game('reinstall-unmanaged');
  // A new dependency may be installed; a manually installed shared dependency
  // already in place cannot be assumed to belong to the translator.
  fs.unlinkSync(path.join(profile.path, COMMON));
  const preview = await previewTranslatorMaintenance(reg, profile, { targetLanguage: 'ko' });
  assert.equal(preview.reinstallEligible, true);
  const events: string[] = [];
  const result = await withDownload(preview, replacement(), () => runTranslatorMaintenance(preview, 'reinstall', { ...cache('unmanaged'), onEvent: (event) => events.push(`${event.phase}:${event.status}`) }));
  assert.equal(result.mutationStatus, 'committed');
  assert.equal(bytes(profile.path, CONFIG).toString(), USER_CONFIG);
  assert.equal(bytes(profile.path, FONT).toString(), 'installed user font');
  assert.ok(events.indexOf('download:completed') < events.indexOf('backup:started'));
  const receipt = result.receipts[0]!;
  assert.ok(receipt.entries.every((entry) => entry.operation === 'create'));
  await uninstallReceipt(receipt, { root: profile.path });
  assert.equal(fs.existsSync(path.join(profile.path, PLUGIN)), false);
  assert.equal(fs.existsSync(path.join(profile.path, COMMON)), false);
  assert.equal(bytes(profile.path, CONFIG).toString(), USER_CONFIG, 'pre-existing user config was never taken into new ownership');
});

test('managed reinstall inherits original modify baselines, untouched config entries and font chronology', async () => {
  const profile = game('managed-baseline');
  const baseline = '.indiedeck/backups/original/BepInEx/plugins/XUnity.AutoTranslator/XUnity.AutoTranslator.Plugin.Core.dll';
  fs.mkdirSync(path.dirname(path.join(profile.path, baseline)), { recursive: true });
  fs.writeFileSync(path.join(profile.path, baseline), 'original pre-IndieDeck file');
  const old = own(profile, [
    { path: PLUGIN, operation: 'modify', backup: baseline, sha256: sha256(bytes(profile.path, PLUGIN)) },
    ...createEntries(profile.path, [COMMON, CONFIG, FONT]),
  ]);
  writeReceiptFile(profile.path, { kind: 'font', componentId: FONT, entries: createEntries(profile.path, [FONT]) });
  const fontReceipt = bytes(profile.path, `.indiedeck/receipts/font-${FONT}.json`);
  const preview = await previewTranslatorMaintenance(reg, profile, { targetLanguage: 'ko' });
  const result = await withDownload(preview, replacement(), () => runTranslatorMaintenance(preview, 'reinstall', cache('managed')));
  const receipt = result.receipts[0]!;
  assert.equal(receipt.entries.find((entry) => entry.path === PLUGIN)?.backup, baseline);
  assert.equal(receipt.entries.find((entry) => entry.path === PLUGIN)?.operation, 'modify');
  assert.equal(receipt.installedAt, old.installedAt);
  assert.deepEqual(receipt.entries.find((entry) => entry.path === CONFIG), (old.entries as InstallReceipt['entries']).find((entry) => entry.path === CONFIG));
  assert.deepEqual(bytes(profile.path, `.indiedeck/receipts/font-${FONT}.json`), fontReceipt);
  assert.equal(bytes(profile.path, CONFIG).toString(), USER_CONFIG);
  await uninstallReceipt(receipt, { root: profile.path });
  assert.equal(bytes(profile.path, PLUGIN).toString(), 'original pre-IndieDeck file', 'restore earliest baseline, not 5.5.2 superseded payload');
});

test('unknown file inside a dedicated translator tree blocks removal rather than broad-deleting it', async () => {
  const profile = game('unknown-file', { 'BepInEx/plugins/XUnity.AutoTranslator/MyCustomMod.dll': 'user plugin' });
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, false);
  assert.equal(preview.blockReasonKey, 'ui.maintenance.reason.unknownFile');
  assert.equal(bytes(profile.path, PLUGIN).length > 0, true);
});

test('cumulative recognised payload size is bounded before a quarantine snapshot can allocate many large files', async () => {
  const large = Buffer.alloc(27 * 1024 * 1024, 0x20);
  const files = Object.fromEntries(['XUnity.Common', 'XUnity.AutoTranslator.Plugin.Core', 'XUnity.AutoTranslator.Plugin.ExtProtocol', 'ExIni', 'XUnity.ResourceRedirector']
    .map((stem) => [`UserLibs/${stem}.dll`, large]));
  const profile = game('cumulative-budget', files);
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, false);
  assert.equal(preview.blockReasonKey, 'ui.maintenance.reason.unknownFile');
  assert.equal(fs.existsSync(path.join(profile.path, '.indiedeck')), false);
  assert.deepEqual(bytes(profile.path, PLUGIN), dllWithVersion('5.5.2'));
});

test('damaged, legacy, arbitrary ownership and missing baseline receipts block cleanup', async () => {
  for (const variant of ['corrupt', 'legacy', 'unrelated-entry', 'missing-baseline']) {
    const profile = game(`unsafe-${variant}`);
    if (variant === 'corrupt') {
      fs.mkdirSync(path.dirname(path.join(profile.path, RECEIPT)), { recursive: true });
      fs.writeFileSync(path.join(profile.path, RECEIPT), '{ not JSON');
    } else if (variant === 'legacy') writeReceiptFile(profile.path, { schemaVersion: 1, entries: [] });
    else if (variant === 'unrelated-entry') own(profile, createEntries(profile.path, [OTHER]));
    else own(profile, [{ path: PLUGIN, operation: 'modify', sha256: sha256(bytes(profile.path, PLUGIN)), backup: '.indiedeck/backups/absent.dll' }]);
    const preview = await previewTranslatorMaintenance(reg, profile);
    assert.equal(preview.removeEligible, false, variant);
    assert.ok(['ui.maintenance.reason.receipt', 'ui.maintenance.reason.ownership'].includes(preview.blockReasonKey!));
    assert.equal(fs.existsSync(path.join(profile.path, PLUGIN)), true);
  }
});

test('an unrelated receipt claiming translator payload blocks cleanup, while its shared components remain preserved', async () => {
  const profile = game('other-owner');
  writeReceiptFile(profile.path, { kind: 'mod', componentId: 'my-mod', entries: createEntries(profile.path, [PLUGIN]) });
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, false);
  assert.equal(preview.blockReasonKey, 'ui.maintenance.reason.ownership');
  const sharedProfile = game('other-shared-owner');
  writeReceiptFile(sharedProfile.path, { kind: 'mod', componentId: 'my-mod', entries: createEntries(sharedProfile.path, [COMMON]) });
  const shared = await previewTranslatorMaintenance(reg, sharedProfile);
  assert.equal(shared.removeEligible, true);
  assert.equal(shared.reinstallEligible, false);
  assert.equal(shared.reinstallBlockReasonKey, 'ui.maintenance.reason.ownership');
  assert.ok(!shared.files.some((file) => file.path === COMMON));
  assert.ok(shared.preservedPaths.includes(COMMON));
});

test('manually installed shared MonoMod libraries are never cleanup files and cannot be overwritten during reinstall', async () => {
  const shared = 'BepInEx/core/MonoMod.RuntimeDetour.dll';
  const profile = game('shared-unmanaged', { [shared]: 'other mod runtime' });
  own(profile, createEntries(profile.path, [COMMON]));
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, true);
  assert.ok(!preview.files.some((file) => file.path === shared));
  await withDownload(preview, zip({ [PLUGIN]: dllWithVersion('5.6.1'), [shared]: 'new runtime' }), async () => {
    await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache('shared-unmanaged')), /ui\.maintenance\.reason\.ownership/);
  });
  assert.equal(bytes(profile.path, shared).toString(), 'other mod runtime');
  assert.deepEqual(bytes(profile.path, PLUGIN), dllWithVersion('5.5.2'));
});

test('an unchanged canonical translator-owned shared runtime may be maintained; edited shared runtime blocks everything', async () => {
  const shared = 'BepInEx/core/Mono.Cecil.dll';
  const profile = game('shared-owned', { [shared]: 'owned runtime' });
  own(profile, createEntries(profile.path, [PLUGIN, COMMON, shared]));
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.ok(preview.files.some((file) => file.path === shared && file.managed));
  fs.writeFileSync(path.join(profile.path, shared), 'modified shared runtime');
  const modified = await previewTranslatorMaintenance(reg, profile);
  assert.equal(modified.removeEligible, false);
  assert.equal(modified.blockReasonKey, 'ui.maintenance.reason.ownership');
});

test('unmanaged XUnity.Common and ResourceRedirector standalone components are preserved and fingerprinted, not cleanup authority', async () => {
  const resource = 'BepInEx/plugins/XUnity.ResourceRedirector/XUnity.ResourceRedirector.dll';
  const bridge = 'BepInEx/plugins/XUnity.ResourceRedirector/XUnity.ResourceRedirector.BepInEx.dll';
  const profile = game('standalone-xunity', { [resource]: 'standalone resource redirector', [bridge]: 'standalone bridge' });
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, true);
  for (const rel of [COMMON, resource, bridge]) {
    assert.ok(!preview.files.some((file) => file.path === rel), `${rel} must not be deleted on filename evidence`);
    assert.ok(preview.preservedPaths.includes(rel), `${rel} is explicitly preserved`);
  }
  fs.appendFileSync(path.join(profile.path, resource), ' changed');
  await assert.rejects(runTranslatorMaintenance(preview, 'remove'), /ui\.maintenance\.reason\.stale/);
  const fresh = await previewTranslatorMaintenance(reg, detectGame(reg, profile.path, { deep: true })!);
  const result = await runTranslatorMaintenance(fresh, 'remove');
  assert.equal(result.mutationStatus, 'committed');
  assert.deepEqual(bytes(profile.path, COMMON), dllWithVersion('5.5.2'));
  assert.equal(bytes(profile.path, resource).toString(), 'standalone resource redirector changed');
  assert.equal(bytes(profile.path, bridge).toString(), 'standalone bridge');
});

test('an archive replacing unmanaged XUnity shared components is blocked before translator cleanup', async () => {
  const resource = 'BepInEx/plugins/XUnity.ResourceRedirector/XUnity.ResourceRedirector.dll';
  for (const rel of [COMMON, resource]) {
    const profile = game(`shared-xunity-conflict-${path.basename(rel)}`, { [resource]: 'standalone resource redirector' });
    const preview = await previewTranslatorMaintenance(reg, profile);
    assert.equal(preview.removeEligible, true);
    assert.equal(preview.reinstallEligible, false);
    assert.equal(preview.reinstallBlockReasonKey, 'ui.maintenance.reason.ownership');
    await withDownload(preview, zip({ [PLUGIN]: dllWithVersion('5.6.1'), [rel]: 'archive shared replacement' }), async () => {
      await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache(`shared-xunity-${path.basename(rel)}`)), /ui\.maintenance\.reason\.ownership/);
    });
    assert.deepEqual(bytes(profile.path, PLUGIN), dllWithVersion('5.5.2'));
    assert.deepEqual(bytes(profile.path, COMMON), dllWithVersion('5.5.2'));
    assert.equal(bytes(profile.path, resource).toString(), 'standalone resource redirector');
    assert.equal(fs.existsSync(path.join(profile.path, RECEIPT)), false);
  }
});

test('preflight shared-component conflicts are variant-specific and reject without downloading, while core-only manual reinstall remains available', async () => {
  const unused = 'UserLibs/XUnity.Common.dll';
  const profile = game('shared-variant-scope', { [unused]: 'unrelated MelonLoader component' });
  own(profile, createEntries(profile.path, [COMMON]));
  const preview = await previewTranslatorMaintenance(reg, profile, { variantId: 'bepinex' });
  assert.equal(preview.reinstallEligible, true, 'BepInEx must not be blocked by an unrelated UserLibs standalone component');
  assert.ok(preview.preservedPaths.includes(unused));
  assert.ok(!preview.files.some((file) => file.path === unused));
  const blockedProfile = game('shared-preflight-download');
  const blocked = await previewTranslatorMaintenance(reg, blockedProfile);
  assert.equal(blocked.removeEligible, true);
  assert.equal(blocked.reinstallEligible, false);
  assert.equal(blocked.reinstallBlockReasonKey, 'ui.maintenance.reason.ownership');
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error('unexpected download of a preflight-blocked plan'); };
  try { await assert.rejects(runTranslatorMaintenance(blocked, 'reinstall'), /ui\.maintenance\.reason\.ownership/); }
  finally { globalThis.fetch = originalFetch; }
  fs.unlinkSync(path.join(blockedProfile.path, COMMON));
  const coreOnly = await previewTranslatorMaintenance(reg, detectGame(reg, blockedProfile.path, { deep: true })!);
  assert.equal(coreOnly.reinstallEligible, true, 'a manually installed core-only translator has no unmanaged guaranteed dependency conflict');
});

test('all four pinned v5.6.1 package layouts admit the exact FullNET executors and protocol DLL', async () => {
  for (const variant of ['bepinex', 'bepinex-il2cpp', 'melonmod', 'melonmod-il2cpp']) {
    let profile = game(`upstream-layout-${variant}`);
    const root = profile.path;
    const melon = variant.startsWith('melonmod');
    const il2cpp = variant.endsWith('il2cpp');
    const put = (rel: string, content: Buffer | string) => {
      fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
      fs.writeFileSync(path.join(root, rel), content);
    };
    if (melon) {
      fs.unlinkSync(path.join(root, LOADER));
      put('MelonLoader/net6/MelonLoader.dll', dllWithVersion('0.7.0'));
    } else if (il2cpp) {
      put('BepInEx/core/BepInEx.Core.dll', dllWithVersion('6.0.0-be.785'));
      put('BepInEx/core/BepInEx.Unity.IL2CPP.dll', dllWithVersion('6.0.0-be.785'));
    }
    if (il2cpp) {
      put('GameAssembly.dll', fakeExe(0x8664));
      put('Game_Data/il2cpp_data/Metadata/global-metadata.dat', 'isolated metadata');
    }
    profile = detectGame(reg, root, { deep: true })!;
    assert.equal(profile.unity?.backend, il2cpp ? 'il2cpp' : 'mono');
    own(profile, createEntries(root, [PLUGIN, COMMON]));
    const preview = await previewTranslatorMaintenance(reg, profile, { targetLanguage: 'ko', variantId: variant });
    assert.equal(preview.reinstallEligible, true, variant);
    assert.equal(preview.variantId, variant);
    const base = melon ? 'UserLibs' : 'BepInEx/plugins/XUnity.AutoTranslator';
    const main = melon ? 'Mods/XUnity.AutoTranslator.Plugin.MelonMod.dll' : PLUGIN;
    const fullNet = `${base}/Translators/FullNET`;
    const names = [
      `${fullNet}/ezTransXP.ExtProtocol.exe`, `${fullNet}/Lec.ExtProtocol.exe`,
      `${fullNet}/XUnity.AutoTranslator.Plugin.ExtProtocol.dll`,
    ];
    const files = {
      [main]: dllWithVersion('5.6.1'),
      ...Object.fromEntries(names.map((name) => [name, 'offline fixture matching actual upstream package filename'])),
    };
    const result = await withDownload(preview, zip(files), () => runTranslatorMaintenance(preview, 'reinstall', cache(`upstream-layout-${variant}`)));
    assert.equal(result.mutationStatus, 'committed', variant);
    for (const name of names) assert.ok(result.filesWritten.includes(name), `${variant}: ${name}`);
    const second = await previewTranslatorMaintenance(reg, detectGame(reg, root, { deep: true })!, { variantId: variant });
    assert.equal(second.removeEligible, true, `${variant} layout must also remain removable after installation`);
    for (const name of names) assert.ok(second.files.some((file) => file.path === name));
  }
});

test('unexpected archive files and bad CRC are rejected before deletion or receipt mutation', async () => {
  for (const variant of ['game-exe', 'crc']) {
    const profile = game(`archive-${variant}`);
    fs.unlinkSync(path.join(profile.path, COMMON));
    const preview = await previewTranslatorMaintenance(reg, profile);
    let archive = zip({ [PLUGIN]: dllWithVersion('5.6.1'), ...(variant === 'game-exe' ? { 'Game.exe': 'malicious replacement' } : {}) });
    if (variant === 'crc') archive[30 + Buffer.byteLength(PLUGIN)]! ^= 1;
    await withDownload(preview, archive, async () => {
      await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache(`archive-${variant}`)), /ui\.maintenance\.reason\.archive/);
    });
    assert.deepEqual(bytes(profile.path, PLUGIN), dllWithVersion('5.5.2'));
    assert.deepEqual(bytes(profile.path, 'Game.exe'), fakeExe(0x8664));
    assert.equal(fs.existsSync(path.join(profile.path, RECEIPT)), false);
  }
});

test('encrypted/link-attributed archives and forged-size deflate bombs are rejected with bounded decompression before cleanup', async () => {
  for (const variant of ['encrypted', 'link', 'bomb']) {
    const profile = game(`archive-${variant}`);
    fs.unlinkSync(path.join(profile.path, COMMON));
    const preview = await previewTranslatorMaintenance(reg, profile);
    const archive = variant === 'bomb'
      ? zip({ [PLUGIN]: Buffer.alloc(33 * 1024 * 1024) }, true, 1)
      : zip({ [PLUGIN]: dllWithVersion('5.6.1') });
    const central = archive.readUInt32LE(archive.length - 22 + 16);
    if (variant === 'encrypted') { archive.writeUInt16LE(1, 6); archive.writeUInt16LE(1, central + 8); }
    if (variant === 'link') archive.writeUInt32LE(0xa0000000, central + 38);
    await withDownload(preview, archive, async () => {
      await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache(`archive-${variant}`)), /ui\.maintenance\.reason\.archive/);
    });
    assert.deepEqual(bytes(profile.path, PLUGIN), dllWithVersion('5.5.2'));
    assert.equal(fs.existsSync(path.join(profile.path, RECEIPT)), false);
  }
});

test('payload edits, game executable changes, host changes and newly added unknown files invalidate an approved preview', async () => {
  for (const variant of ['payload', 'game', 'host', 'unknown']) {
    const profile = game(`stale-${variant}`);
    const preview = await previewTranslatorMaintenance(reg, profile);
    if (variant === 'payload') fs.appendFileSync(path.join(profile.path, PLUGIN), 'changed');
    if (variant === 'game') fs.writeFileSync(path.join(profile.path, 'Game.exe'), fakeExe(0x14c));
    if (variant === 'host') fs.writeFileSync(path.join(profile.path, LOADER), dllWithVersion('6.0.0'));
    if (variant === 'unknown') fs.writeFileSync(path.join(profile.path, 'BepInEx/plugins/XUnity.AutoTranslator/custom.txt'), 'keep');
    await assert.rejects(runTranslatorMaintenance(preview, 'remove'), /ui\.maintenance\.reason\.stale/, variant);
    assert.equal(fs.existsSync(path.join(profile.path, PLUGIN)), true);
  }
});

test('a game changed during download is revalidated before any cleanup', async () => {
  const profile = game('stale-download');
  fs.unlinkSync(path.join(profile.path, COMMON));
  const preview = await previewTranslatorMaintenance(reg, profile);
  await withDownload(preview, replacement(), async () => {
    await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache('stale-download')), /ui\.maintenance\.reason\.stale/);
  }, () => fs.appendFileSync(path.join(profile.path, PLUGIN), 'external edit'));
  assert.ok(bytes(profile.path, PLUGIN).toString().includes('external edit'));
});

test('receipt write failure restores all pre-operation payload and old receipt bytes from the retained quarantine', async () => {
  const profile = game('receipt-fault');
  own(profile, createEntries(profile.path, [PLUGIN, COMMON, CONFIG]));
  const originalReceipt = bytes(profile.path, RECEIPT);
  const preview = await previewTranslatorMaintenance(reg, profile);
  const originalOpen = fsp.open;
  let failOnce = true;
  fsp.open = (async (...args: Parameters<typeof fsp.open>) => {
    if (String(args[0]) === path.join(profile.path, RECEIPT) && typeof args[1] === 'number' && (args[1] & 3) === 2 && failOnce) {
      failOnce = false; throw new Error('isolated receipt write failure');
    }
    return originalOpen(...args);
  }) as typeof fsp.open;
  try {
    await withDownload(preview, replacement(), async () => {
      await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache('receipt-fault')), (error: unknown) => {
        const result = (error as { maintenanceResult?: { mutationStatus: string; rollbackStatus: string; backupDirectory: string } }).maintenanceResult;
        assert.equal(result?.mutationStatus, 'rolled-back');
        assert.equal(result?.rollbackStatus, 'complete');
        assert.ok(fs.existsSync(result!.backupDirectory));
        return true;
      });
    });
  } finally { fsp.open = originalOpen; }
  assert.deepEqual(bytes(profile.path, RECEIPT), originalReceipt);
  assert.deepEqual(bytes(profile.path, PLUGIN), dllWithVersion('5.5.2'));
  assert.deepEqual(bytes(profile.path, COMMON), dllWithVersion('5.5.2'));
  assert.equal(bytes(profile.path, CONFIG).toString(), USER_CONFIG);
});

test('a recovery I/O failure reports partial state honestly and retains the pre-operation backup', async () => {
  const profile = game('partial-recovery');
  own(profile, createEntries(profile.path, [PLUGIN, COMMON, CONFIG]));
  const preview = await previewTranslatorMaintenance(reg, profile);
  const originalOpen = fsp.open, originalWrite = fsp.writeFile;
  let failReceipt = true;
  fsp.open = (async (...args: Parameters<typeof fsp.open>) => {
    if (String(args[0]) === path.join(profile.path, RECEIPT) && typeof args[1] === 'number' && (args[1] & 3) === 2 && failReceipt) {
      failReceipt = false; throw new Error('isolated receipt commit failure');
    }
    return originalOpen(...args);
  }) as typeof fsp.open;
  fsp.writeFile = (async (...args: Parameters<typeof fsp.writeFile>) => {
    if (String(args[0]) === path.join(profile.path, PLUGIN)) throw new Error('isolated recovery write failure');
    return originalWrite(...args);
  }) as typeof fsp.writeFile;
  try {
    await withDownload(preview, replacement(), async () => {
      await assert.rejects(runTranslatorMaintenance(preview, 'reinstall', cache('partial-recovery')), (error: unknown) => {
        const result = (error as { maintenanceResult?: { mutationStatus: string; rollbackStatus: string; backupDirectory: string; rollbackFailures: { path: string }[] } }).maintenanceResult;
        assert.equal(result?.mutationStatus, 'partial');
        assert.equal(result?.rollbackStatus, 'partial');
        assert.ok(result?.rollbackFailures.some((failure) => failure.path === PLUGIN));
        assert.deepEqual(fs.readFileSync(path.join(result!.backupDirectory, 'files', PLUGIN)), dllWithVersion('5.5.2'));
        return true;
      });
    });
  } finally { fsp.open = originalOpen; fsp.writeFile = originalWrite; }
  assert.equal(bytes(profile.path, CONFIG).toString(), USER_CONFIG);
  assert.equal(bytes(profile.path, OTHER).toString(), 'another user-owned mod');
});

test('junctions in payload or backup ancestors are rejected without touching external data', async (ctx: TestContext) => {
  const profile = game('junction');
  const outside = makeGame('translator-maintenance-outside', { 'sentinel.txt': 'keep outside' });
  fs.mkdirSync(path.join(profile.path, '.indiedeck'), { recursive: true });
  try { fs.symlinkSync(outside, path.join(profile.path, '.indiedeck/backups'), process.platform === 'win32' ? 'junction' : 'dir'); }
  catch (error) {
    if (['EPERM', 'EACCES', 'ENOTSUP'].includes((error as NodeJS.ErrnoException).code ?? '')) { ctx.skip('isolated junction creation is unavailable'); return; }
    throw error;
  }
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, false);
  assert.equal(preview.blockReasonKey, 'ui.maintenance.reason.linkedPath');
  assert.equal(bytes(outside, 'sentinel.txt').toString(), 'keep outside');
});

test('ReiPatcher is blocked rather than deleting a patcher or pretending game assemblies can be safely unpatched', async () => {
  const profile = game('reipatcher', { 'ReiPatcher/ReiPatcher.exe': fakeExe(0x14c) });
  const preview = await previewTranslatorMaintenance(reg, profile);
  assert.equal(preview.removeEligible, false);
  assert.equal(preview.blockReasonKey, 'ui.maintenance.reason.host');
});
