import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { after, test } from 'node:test';
import zlib from 'node:zlib';
import { detectGame } from '../src/detect/index.ts';
import { readReceipts, uninstallReceipt, writeReceipt } from '../src/install/apply.ts';
import { FileTransaction, withTransaction } from '../src/install/transaction.ts';
import { installModFromFile } from '../src/mods/index.ts';
import { loadRegistry } from '../src/registry/index.ts';

const reg = loadRegistry();
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'indiedeck-tx-'));
after(() => fs.rmSync(tmp, { recursive: true, force: true }));

function exe(machine = 0x8664): Buffer {
  const b = Buffer.alloc(512);
  b.writeUInt16LE(0x5a4d, 0);
  b.writeUInt32LE(0x80, 0x3c);
  b.writeUInt32LE(0x4550, 0x80);
  b.writeUInt16LE(machine, 0x84);
  return b;
}

function makeZip(files: { name: string; data: Buffer }[]): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;
  for (const file of files) {
    const nameBuf = Buffer.from(file.name, 'utf8');
    const compressed = zlib.deflateRawSync(file.data);
    const local = Buffer.alloc(30 + nameBuf.length);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(8, 8);
    local.writeUInt32LE(compressed.length, 18);
    local.writeUInt32LE(file.data.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    nameBuf.copy(local, 30);
    locals.push(local, compressed);

    const central = Buffer.alloc(46 + nameBuf.length);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(8, 10);
    central.writeUInt32LE(compressed.length, 20);
    central.writeUInt32LE(file.data.length, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt32LE(offset, 42);
    nameBuf.copy(central, 46);
    centrals.push(central);
    offset += local.length + compressed.length;
  }
  const centralBuf = Buffer.concat(centrals);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(files.length, 8);
  eocd.writeUInt16LE(files.length, 10);
  eocd.writeUInt32LE(centralBuf.length, 12);
  eocd.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, centralBuf, eocd]);
}

function makeGame(name: string, files: Record<string, string | Buffer>): string {
  const root = path.join(tmp, name);
  for (const [rel, content] of Object.entries(files)) {
    const target = path.join(root, rel);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
  }
  return root;
}

const ORIGINAL_PLUGINS = `// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin","parameters":{"cacheLimit":"10"}},
{"name":"MadeWithMv","status":true,"description":"Show splash","parameters":{}}
];
`;

function rpgGame(name: string): string {
  return makeGame(name, {
    'Game.exe': exe(),
    'nw.dll': 'stub',
    'package.json': '{"name":"demo"}',
    'js/rmmz_core.js': '//',
    'js/plugins.js': ORIGINAL_PLUGINS,
    'js/plugins/Community_Basic.js': '// existing',
    'data/System.json': JSON.stringify({ gameTitle: 'Demo' }),
  });
}

/* ------------------------------------------------------------------ §81 */

test('removing an RPG Maker plugin restores plugins.js byte for byte', async () => {
  const root = rpgGame('rpg-plugins-roundtrip');
  const before = await fsp.readFile(path.join(root, 'js/plugins.js'));

  const modZip = path.join(tmp, 'questlog.zip');
  await fsp.writeFile(modZip, makeZip([{ name: 'QuestLog.js', data: Buffer.from('// quest log') }]));

  const profile = detectGame(reg, root)!;
  await installModFromFile(reg, profile, modZip, { name: 'QuestLog' });

  const afterInstall = await fsp.readFile(path.join(root, 'js/plugins.js'), 'utf8');
  assert.match(afterInstall, /QuestLog/, 'the plugin is registered in plugins.js');
  assert.match(afterInstall, /Community_Basic/, 'existing entries survive the edit');

  const receipts = await readReceipts(root);
  const receipt = receipts.find((r) => r.componentId === 'QuestLog');
  assert.ok(receipt, 'the install wrote a receipt');

  await uninstallReceipt(receipt);

  assert.equal(fs.existsSync(path.join(root, 'js/plugins/QuestLog.js')), false, 'the plugin file is gone');
  assert.ok(fs.existsSync(path.join(root, 'js/plugins.js')), 'plugins.js still exists');
  assert.deepEqual(
    await fsp.readFile(path.join(root, 'js/plugins.js')),
    before,
    'plugins.js is restored byte for byte, including comments and formatting',
  );
});

/* ------------------------------------------------------------------ §11 */

test('a mod that overwrites an existing file restores it on uninstall', async () => {
  const root = rpgGame('rpg-overwrite');
  const originalPlugin = await fsp.readFile(path.join(root, 'js/plugins/Community_Basic.js'));

  const modZip = path.join(tmp, 'overwriting.zip');
  await fsp.writeFile(
    modZip,
    makeZip([
      { name: 'Community_Basic.js', data: Buffer.from('// REPLACED by a mod') },
      { name: 'NewThing.js', data: Buffer.from('// new') },
    ]),
  );

  const profile = detectGame(reg, root)!;
  await installModFromFile(reg, profile, modZip, { name: 'Overwriter' });

  assert.match(
    await fsp.readFile(path.join(root, 'js/plugins/Community_Basic.js'), 'utf8'),
    /REPLACED/,
    'the mod did overwrite the existing file',
  );

  const receipt = (await readReceipts(root)).find((r) => r.componentId === 'Overwriter')!;
  await uninstallReceipt(receipt);

  assert.equal(fs.existsSync(path.join(root, 'js/plugins/NewThing.js')), false, 'files the mod created are removed');
  assert.deepEqual(
    await fsp.readFile(path.join(root, 'js/plugins/Community_Basic.js')),
    originalPlugin,
    'a file the mod displaced is restored, not deleted',
  );
});

/* ------------------------------------------------------------------ §85 */

test('a failed install leaves the game folder exactly as it was', async () => {
  const root = rpgGame('rpg-rollback');
  // One walker, an explicit target map. The earlier version closed over
  // `snapshot` and was called again after the failure, so it re-recorded the
  // post-failure state and the test could not fail.
  const walk = (dir: string, into: Map<string, Buffer>): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full, into);
      else into.set(path.relative(root, full), fs.readFileSync(full));
    }
  };

  const snapshot = new Map<string, Buffer>();
  walk(root, snapshot);

  const broken = path.join(tmp, 'broken.zip');
  await fsp.writeFile(broken, Buffer.from('this is not a zip at all'));

  const profile = detectGame(reg, root)!;
  await assert.rejects(() => installModFromFile(reg, profile, broken, { name: 'Broken' }), /ZIP|zip/);

  const now = new Map<string, Buffer>();
  walk(root, now);

  assert.deepEqual([...now.keys()].sort(), [...snapshot.keys()].sort(), 'no stray files are left behind');
  for (const [rel, content] of snapshot) {
    assert.deepEqual(now.get(rel), content, `${rel} is unchanged`);
  }
});

/* ------------------------------------------------------- transaction core */

test('rollback undoes creates and restores overwrites when a step throws', async () => {
  const root = makeGame('tx-rollback', {
    'keep.txt': 'original content',
    'nested/deep.txt': 'nested original',
  });

  await assert.rejects(
    () =>
      withTransaction({ root, backupDir: '.indiedeck/backups' }, async (tx) => {
        await tx.write('keep.txt', 'clobbered');
        await tx.write('brand-new.txt', 'new file');
        await tx.write('nested/deep.txt', 'clobbered too');
        throw new Error('step 4 exploded');
      }),
    /step 4 exploded/,
  );

  assert.equal(await fsp.readFile(path.join(root, 'keep.txt'), 'utf8'), 'original content');
  assert.equal(await fsp.readFile(path.join(root, 'nested/deep.txt'), 'utf8'), 'nested original');
  assert.equal(fs.existsSync(path.join(root, 'brand-new.txt')), false, 'the created file is gone');
});

test('rollback reports a missing backup instead of claiming complete restoration', async () => {
  const root = makeGame('tx-rollback-report', { 'keep.txt': 'original content' });
  const tx = new FileTransaction({ root, backupDir: '.indiedeck/backups' });
  const entry = await tx.write('keep.txt', 'changed');
  assert.ok(entry.backup);
  await fsp.rm(path.join(root, entry.backup));

  const report = await tx.rollback();
  assert.equal(report.status, 'partial');
  assert.equal(report.attempted, 1);
  assert.equal(report.completed, 0);
  assert.deepEqual(report.failures.map((failure) => failure.path), ['keep.txt']);
  assert.equal(await fsp.readFile(path.join(root, 'keep.txt'), 'utf8'), 'changed');
});

test('the journal marks a displaced file as modify and keeps its backup', async () => {
  const root = makeGame('tx-journal', { 'existing.cfg': 'v1' });
  const { entries } = await withTransaction({ root, backupDir: '.indiedeck/backups' }, async (tx) => {
    await tx.write('existing.cfg', 'v2');
    await tx.write('fresh.cfg', 'v1');
    return undefined;
  });

  const displaced = entries.find((e) => e.path === 'existing.cfg')!;
  const created = entries.find((e) => e.path === 'fresh.cfg')!;
  assert.equal(displaced.operation, 'modify');
  assert.ok(displaced.backup, 'a backup path is recorded');
  assert.equal(await fsp.readFile(path.join(root, displaced.backup!), 'utf8'), 'v1');
  assert.equal(created.operation, 'create');
  assert.equal(created.backup, undefined);
});

test('copyIn records the exact copied-file hash and refuses directory copies before mutation', async () => {
  const root = makeGame('tx-copy-file-evidence', {});
  const source = path.join(tmp, 'tx-copy-file-source.bin');
  const payload = Buffer.from('font or loose-mod payload');
  await fsp.writeFile(source, payload);

  const tx = new FileTransaction({ root, backupDir: '.indiedeck/backups' });
  const entry = await tx.copyIn(source, 'fonts/payload.bin');
  assert.equal(entry.operation, 'create');
  assert.equal(entry.sha256, crypto.createHash('sha256').update(payload).digest('hex'));
  assert.deepEqual(await fsp.readFile(path.join(root, entry.path)), payload);

  const sourceDir = path.join(tmp, 'tx-copy-directory-source');
  await fsp.mkdir(sourceDir, { recursive: true });
  await fsp.writeFile(path.join(sourceDir, 'nested.bin'), 'nested');
  await assert.rejects(
    () => tx.copyIn(sourceDir, 'unsupported-directory'),
    /only supports regular files; directory copies require per-file receipt entries/,
  );
  assert.equal(fs.existsSync(path.join(root, 'unsupported-directory')), false);
  assert.equal(tx.entries.some((item) => item.path === 'unsupported-directory'), false);
});

test('an unsafe mod receipt name is rejected before any mod file is written', async () => {
  const root = rpgGame('rpg-unsafe-receipt-name');
  const source = path.join(tmp, 'unsafe-name-plugin.js');
  await fsp.writeFile(source, '// plugin');
  const profile = detectGame(reg, root)!;

  await assert.rejects(
    () => installModFromFile(reg, profile, source, { name: '../escape' }),
    /safe receipt filename/,
  );
  assert.equal(fs.existsSync(path.join(root, 'js/plugins/unsafe-name-plugin.js')), false);
  assert.equal(fs.existsSync(path.join(root, '.indiedeck')), false);
});

test('uninstall leaves a file alone once the user has edited it', async () => {
  const root = makeGame('tx-handedit', {});
  const { entries } = await withTransaction({ root, backupDir: '.indiedeck/backups' }, async (tx) => {
    await tx.write('mod.dll', 'as installed');
    await tx.write('untouched.dll', 'as installed');
    return undefined;
  });
  const receipt = await writeReceipt(root, { kind: 'mod', componentId: 'Edited', version: 'local', entries });

  await fsp.writeFile(path.join(root, 'mod.dll'), 'user changed this afterwards');
  const result = await uninstallReceipt(receipt);

  assert.deepEqual(result.keptModified, ['mod.dll']);
  assert.equal(await fsp.readFile(path.join(root, 'mod.dll'), 'utf8'), 'user changed this afterwards');
  assert.deepEqual(result.removed, ['untouched.dll']);
  assert.equal(fs.existsSync(path.join(root, 'untouched.dll')), false);
  assert.equal(result.receiptRetained, true, 'unresolved evidence stays available for retry');
  const retained = (await readReceipts(root)).find((item) => item.componentId === 'Edited');
  assert.deepEqual(retained?.entries.map((entry) => entry.path), ['mod.dll'], 'completed entries are pruned from the retained receipt');
});

test('uninstall does not restore over a hand-edited modified file', async () => {
  const root = makeGame('tx-handedit-modify', { 'shared.dll': 'game original' });
  const { entries } = await withTransaction({ root, backupDir: '.indiedeck/backups' }, async (tx) => {
    await tx.write('shared.dll', 'translator version');
    return undefined;
  });
  const receipt = await writeReceipt(root, { kind: 'translator', componentId: 'Shared', version: '1.0', entries });
  await fsp.writeFile(path.join(root, 'shared.dll'), 'user changed translator version');

  const result = await uninstallReceipt(receipt);
  assert.deepEqual(result.keptModified, ['shared.dll']);
  assert.equal(result.receiptRetained, true);
  assert.equal(await fsp.readFile(path.join(root, 'shared.dll'), 'utf8'), 'user changed translator version');
  assert.equal((await readReceipts(root)).some((item) => item.componentId === 'Shared'), true);
});

test('uninstall conservatively retains a changed snapshot without a post-write hash', async () => {
  const root = makeGame('tx-handedit-snapshot', { 'Managed/Game.dll': 'baseline' });
  const { entries } = await withTransaction({ root, backupDir: '.indiedeck/backups' }, async (tx) => {
    await tx.snapshot('Managed');
    return undefined;
  });
  const receipt = await writeReceipt(root, { kind: 'translator', componentId: 'Snapshot', version: '1.0', entries });
  await fsp.writeFile(path.join(root, 'Managed/Game.dll'), 'changed after snapshot');

  const result = await uninstallReceipt(receipt);
  assert.deepEqual(result.keptModified, ['Managed']);
  assert.equal(result.receiptRetained, true);
  assert.equal(await fsp.readFile(path.join(root, 'Managed/Game.dll'), 'utf8'), 'changed after snapshot');
});

test('a schemaVersion 1 receipt still uninstalls, and its backups still restore', async () => {
  const root = makeGame('tx-legacy', { 'game.cfg': 'the original' });
  fs.mkdirSync(path.join(root, '.indiedeck/backups/old'), { recursive: true });
  fs.writeFileSync(path.join(root, '.indiedeck/backups/old/game.cfg'), 'the original');
  fs.writeFileSync(path.join(root, 'game.cfg'), 'installed version');
  fs.writeFileSync(path.join(root, 'plugin.dll'), 'installed');

  const legacy = {
    id: 'legacy-1',
    gamePath: root,
    kind: 'mod' as const,
    componentId: 'Legacy',
    version: '1.0',
    installedAt: new Date(0).toISOString(),
    files: ['plugin.dll', 'game.cfg'],
    backups: [{ original: 'game.cfg', backup: '.indiedeck/backups/old/game.cfg' }],
    entries: [],
  };

  const result = await uninstallReceipt(legacy);
  assert.deepEqual(result.removed, ['plugin.dll'], 'files without a backup are treated as creations');
  assert.deepEqual(result.restored, ['game.cfg'], 'files with a backup are restored, not deleted');
  assert.equal(await fsp.readFile(path.join(root, 'game.cfg'), 'utf8'), 'the original');
});
